[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
example = "wyt78UXHtukcbQsJbRPFGf979jxPMvbEij8qAqNsgUx"
tossbounty = "F6xSV3U35V8stCdd1zpuVujRVZm9LimfG3YhRT2csUGm"
tossbounty_pauser = "9AUryp328sF7BKnv63arhPvrqHNqmwpQEvm7ry6oEnHh"

[programs.localnet]
example = "wyt78UXHtukcbQsJbRPFGf979jxPMvbEij8qAqNsgUx"
tossbounty = "F6xSV3U35V8stCdd1zpuVujRVZm9LimfG3YhRT2csUGm"
tossbounty_pauser = "9AUryp328sF7BKnv63arhPvrqHNqmwpQEvm7ry6oEnHh"

[programs.mainnet]
tossbounty = "BYzWEaZXS7Zf4SY6dcqnsjySp9qLEmB9C3WvyigxtpYQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/thomasrodriguez/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
